package com.example.appa.data;


import android.database.Cursor;

import androidx.room.Dao;
import androidx.room.Insert;
import androidx.room.Query;
import androidx.room.Update;
import androidx.room.Delete;

// DAO (Data Access Object) for the albums table
//why Cursor methods?
// 1) ContentProviders typically return a Cursor from the query()
// 2) Room supports returning Cursor directly which makes it easy for appa's ContentProvider to serve data to App B through ContentResolver

@Dao
public interface AlbumDao {

    // Returns ALL albums as a Cursor (used by ContentProvider query on /albums)
    // ORDER BY id DESC shows newest inserts first
    @Query("SELECT id, title, artist FROM albums ORDER BY id DESC")
    Cursor getAllAsCursor();

    // Returns ONE album as a Cursor (used by ContentProvider query on /albums/<id>)
    // id is the primary key so it should match at most one row
    @Query("SELECT id, title, artist FROM albums WHERE id = :id")
    Cursor getByIdAsCursor(long id);

    // Inserts a new album row
    //  Returns the new row ID generated by SQLite (because id is autoGenerate=true)
    @Insert
    long insert(AlbumEntity album);

    // Updates a row by id
    // Returns number of rows updated (0 if id not found, 1 if success)
    @Query("UPDATE albums SET title = :title, artist = :artist WHERE id = :id")
    int updateById(long id, String title, String artist);

    // Deletes a row by id
    //  then Returns number of rows deleted (0 if id not found, 1 if success)
    @Query("DELETE FROM albums WHERE id = :id")
    int deleteById(long id);




}
